name: Backend Tests

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run backend tests with Docker Compose
        run: docker-compose -p crm-test -f docker-compose.test.yml run --rm backend-test
